# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run docs:build
      env:
        CI: true
    - run: |
         git status
         git remote -v
         git branch -a
         git fetch -a
         git branch -a
         pwd
         ls
         ls -al MVI1/
         mkdir workdir
         cd workdir/
         git clone -b gh-pages https://x-access-token:$MYTOKEN@github.com/gabrielmcg/testaction.git
         cd testaction
         git status
         ls -al
         cp -r ../../MVI1/ .
         git config --local user.email "action@github.com"        
         git config --local user.name "GitHub Action"

         git status
         git add .
         git commit -m "update docs"
         git push
      env:
        MYTOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}  
         

         
         
         
         

         
